### ISSUE TITLE
m1.dcos Connection refused

### ISSUE THREAD

**Issue by liuq4360** [dcos/dcos-vagrant#46]
When I install dcos-vagrant follow the steps, then is no error during the installation,but when i curl m1.dcos there is some thing wrong:

moretv@moretv-desktop:~/vagrant/dcos-vagrant$ curl http://m1.dcos
curl: (7) Failed to connect to m1.dcos port 80: Connection refused

**Comment by karlkfi** [comment]
Did you install the vagrant-hostmanager plugin? It handles setting up your /etc/hosts so that the m1.dcos host works. 

Alternatively it could be that one of the DC/OS components is failing. You can vagrant ssh into the nodes and check the systemd service status or the journald service logs. Most of the critical services start with dcos-

**Comment by karlkfi** [comment]
Closing from lack of feedback.
